name: Monitor JNE

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar monitor
        run: python monitor_jne.py
      - name: Guardar estado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar seen.json"
